CREATE TABLE IF NOT EXISTS student
(
    id    BIGSERIAL PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    age INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS faculty
(
    id    BIGSERIAL PRIMARY KEY ,
    name  VARCHAR(200) NOT NULL ,
    color VARCHAR(200) NOT NULL
);